version: "3.8"

services:
  image-processing-api:
    image: image-processing-api:latest
    container_name: image-processing-api
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:8.0.11-noble
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: