version: "3.8"

services:
  mongodb:
    image: mongo:8.0.11-noble
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: